#pragma once

#define BINARY_DATA "application/octet-stream"

#define PLAIN_TEXT "text/plain"
#define HTML "text/html"
#define CSS "text/css"
#define JAVASCRIPT "text/javascript"
#define CSV "text/csv"

#define JSON "application/json"
#define XML "application/xml"
#define ZIP "application/zip"
#define Z7 "application/x-7z-compressed"
#define PDF "application/pdf"

#define PNG "image/png"
#define GIF "image/gif"
#define BMP "image/bmp"
#define JPEG "image/jpeg"
#define WEBP "image/webp"
#define APNG "image/apng"
#define SVG "image/svg+xml"
#define ICO "image/vnd.microsoft.icon"
#define AVIF "image/avif"
#define TIFF "image/tiff"

#define WEBA "audio/webm"
#define MIDI "audio/midi"
#define WAV "audio/wav"
#define MP3 "audio/mpeg"
#define AAC "audio/aac"
#define OGA "audio/ogg"
#define OPUS "audio/opus"

#define WEBM "video/webm"
#define MP4 "video/mp4"
#define MPEG "video/mpeg"
#define OGV "video/ogg"
#define TS "video/mp2t"

#define DOC "application/msword"
#define DOCX "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
#define PPT "application/vnd.ms-powerpoint"
#define PPTX "application/vnd.openxmlformats-officedocument.presentationml.presentation"
#define XLS "application/vnd.ms-excel"
#define XLSX "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
#define ABW "application/x-abiword"
#define ARC "application/x-freearc"
#define BIN "application/octet-stream"
#define CDA "application/x-cdf"
#define CSH "application/x-csh"
#define EPUB "application/epub+zip"
#define GZ "application/gzip"
#define JAR "application/java-archive"
#define MPKG "application/vnd.apple.installer+xml"
#define ODP "application/vnd.oasis.opendocument.presentation"
#define ODS "application/vnd.oasis.opendocument.spreadsheet"
#define ODT "application/vnd.oasis.opendocument.text"
#define OGX "application/ogg"
#define PHP "application/x-httpd-php"
#define RAR "application/vnd.rar"
#define RTF "application/rtf"
#define SH "application/x-sh"
#define TAR "application/x-tar"
#define VSD "application/vnd.visio"
#define XHTML "application/xhtml+xml"
#define XUL "application/vnd.mozilla.xul+xml"

#define OTF "font/otf"
#define TTF "font/ttf"
#define WOFF "font/woff"
#define WOFF2 "font/woff2"
